(function() {
  var style = document.createElement('style');
  style.textContent = '#chat-bubble{position:fixed;bottom:24px;right:24px;width:56px;height:56px;background:#0d1f2d;border-radius:50%;display:flex;align-items:center;justify-content:center;cursor:pointer;z-index:9999;box-shadow:0 4px 16px rgba(0,0,0,0.3);border:none;}#chat-bubble svg{width:28px;height:28px;fill:#c9a84c;}#chat-window{position:fixed;bottom:90px;right:24px;width:340px;height:480px;background:#fff;border-radius:16px;box-shadow:0 8px 32px rgba(0,0,0,0.2);display:none;flex-direction:column;z-index:9999;overflow:hidden;font-family:sans-serif;}#chat-header{background:#0d1f2d;color:#fff;padding:16px 20px;display:flex;justify-content:space-between;align-items:center;}#chat-header h4{margin:0;font-size:15px;}#chat-header span{font-size:11px;color:#c9a84c;}#chat-close{background:none;border:none;color:#fff;font-size:20px;cursor:pointer;}#chat-messages{flex:1;overflow-y:auto;padding:16px;display:flex;flex-direction:column;gap:12px;}#chat-messages .msg{max-width:85%;padding:10px 14px;border-radius:12px;font-size:14px;line-height:1.5;}#chat-messages .bot{background:#f0ede8;color:#0d1f2d;align-self:flex-start;}#chat-messages .user{background:#0d1f2d;color:#fff;align-self:flex-end;}#chat-messages .typing{background:#f0ede8;color:#777;font-style:italic;align-self:flex-start;}#chat-input-area{padding:12px;border-top:1px solid #eee;display:flex;gap:8px;}#chat-input{flex:1;border:1px solid #ddd;border-radius:8px;padding:10px;font-size:14px;outline:none;}#chat-send{background:#0d1f2d;color:#fff;border:none;border-radius:8px;padding:10px 16px;cursor:pointer;font-size:14px;font-weight:600;}';
  document.head.appendChild(style);
  var html = '<button id="chat-bubble" onclick="toggleChat()"><svg viewBox="0 0 24 24"><path d="M12 2C6.48 2 2 6.48 2 12c0 1.85.5 3.58 1.37 5.07L2 22l4.93-1.37A9.94 9.94 0 0012 22c5.52 0 10-4.48 10-10S17.52 2 12 2zm1 15H7v-2h6v2zm2-4H7v-2h8v2zm0-4H7V7h8v2z"/></svg></button><div id="chat-window"><div id="chat-header"><div><h4>🏠 Sawyers Premier Realty</h4><span>Ask me anything!</span></div><button id="chat-close" onclick="toggleChat()">✕</button></div><div id="chat-messages"><div class="msg bot">Hi! I am Angela\'s virtual assistant. Ask me about buying, selling, rentals, notary services, or our Hollis Ave listing!</div></div><div id="chat-input-area"><input id="chat-input" type="text" placeholder="Type a question..."/><button id="chat-send">Send</button></div></div>';
  document.body.insertAdjacentHTML('beforeend', html);
  document.getElementById('chat-input').addEventListener('keydown', function(e){if(e.key==='Enter')sendMsg();});
  document.getElementById('chat-send').addEventListener('click', sendMsg);
  window.toggleChat = function(){var w=document.getElementById('chat-window');w.style.display=w.style.display==='flex'?'none':'flex';};
  async function sendMsg(){var input=document.getElementById('chat-input');var messages=document.getElementById('chat-messages');var text=input.value.trim();if(!text)return;messages.innerHTML+='<div class="msg user">'+text+'</div>';input.value='';messages.scrollTop=messages.scrollHeight;var typing=document.createElement('div');typing.className='msg typing';typing.id='typing';typing.textContent='Angela is typing...';messages.appendChild(typing);messages.scrollTop=messages.scrollHeight;try{var res=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'claude-sonnet-4-20250514',max_tokens:300,system:'You are a helpful assistant for Sawyers Premier Realty in Elmont NY run by Angela Sawyers. Be warm and concise 2-3 sentences max. Services: buying selling rentals notary loan modification commercial and investment properties. Location: 1389 Hempstead Tpke 2nd Fl Elmont NY 11003. Phone: (516) 216-1394. Hours: Mon-Sun 10am-7pm. Current listing: 210-05 Hollis Ave Queens Village NY 6-unit multi-family $2100000 off-market. Always end with a call to action.',messages:[{role:'user',content:text}]})});var data=await res.json();document.getElementById('typing').remove();messages.innerHTML+='<div class="msg bot">'+data.content[0].text+'</div>';}catch(e){document.getElementById('typing').remove();messages.innerHTML+='<div class="msg bot">Sorry, please call us at (516) 216-1394!</div>';}messages.scrollTop=messages.scrollHeight;}
})();
